# Generated by Django 2.0.1 on 2018-01-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180118_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='inrtoduction',
            new_name='introduction',
        ),
    ]
